add support for interactive selection with fzf
present a fuzzy search choice in "kubectx" and "kubens" commands without
arguments.

Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>

diff --git a/kubectx b/kubectx
--- a/kubectx
+++ b/kubectx
@@ -89,6 +89,17 @@ switch_context() {
   kubectl config use-context "${1}"
 }
 
+choose_context_interactive() {
+  local choice
+  choice="$(FZF_DEFAULT_COMMAND='kubectx' fzf --ansi || true)"
+  if [[ -z "${choice}" ]]; then
+    echo 2>&1 "error: you did not choose any of the options"
+    exit 1
+  else
+    set_context "${choice}"
+  fi
+}
+
 set_context() {
   local prev
   prev="$(current_context)"
@@ -170,7 +181,11 @@ delete_context() {
 
 main() {
   if [[ "$#" -eq 0 ]]; then
-    list_contexts
+    if [[ -t 1 && "$(type fzf &>/dev/null; echo $?)" -eq 0 ]]; then
+      choose_context_interactive
+    else
+      list_contexts
+    fi
   elif [[ "${1}" == "-d" ]]; then
     if [[ "$#" -lt 2 ]]; then
       echo "error: missing context NAME" >&2
diff --git a/kubens b/kubens
--- a/kubens
+++ b/kubens
@@ -85,6 +85,25 @@ switch_namespace() {
   echo "Active namespace is \"${2}\".">&2
 }
 
+choose_namespace_interactive() {
+  # directly calling kubens via fzf might fail with a cryptic error like
+  # "$FZF_DEFAULT_COMMAND failed", so try to see if we can list namespaces
+  # locally first
+  if [[ -z "$(list_namespaces)" ]]; then
+    echo >&2 "error: could not list namespaces (is the cluster accessible?)"
+    exit 1
+  fi
+
+  local choice
+  choice="$(FZF_DEFAULT_COMMAND='kubens' fzf --ansi || true)"
+  if [[ -z "${choice}" ]]; then
+    echo 2>&1 "error: you did not choose any of the options"
+    exit 1
+  else
+    set_namespace "${choice}"
+  fi
+}
+
 set_namespace() {
   local ctx prev
   ctx="$(current_context)"
@@ -137,7 +156,11 @@ swap_namespace() {
 
 main() {
   if [[ "$#" -eq 0 ]]; then
-    list_namespaces
+    if [[ -t 1 && "$(type fzf &>/dev/null; echo $?)" -eq 0 ]]; then
+      choose_namespace_interactive
+    else
+      list_namespaces
+    fi
   elif [[ "$#" -eq 1 ]]; then
     if [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
       usage
